---
- name: Install software
  ansible.builtin.apt:
    name:
      - git
      - ansible
      - exfat-fuse
      - gtkhash
      - virtualbox
      - virtualbox-ext-pack
      - libglib2.0-dev
      - network-manager-openconnect-gnome
      - gnome-session
      - gnome-screenshot
      - ubuntu-restricted-extras
      - timeshift
    state: present
  become: true
