---
- name: Download broadcom-wl
  ansible.builtin.git:
    repo: 'https://github.com/antoineco/broadcom-wl.git'
    dest: ./broadcom-wl

- name: Verify needed packages
  ansible.builtin.dnf:
    name: 
      - kernel-devel
      - broadcom-wl
      - dkms
    state: present

- name: Install kernel module
  ansible.builtin.command:
    cmd: dkms add ./broadcom-wl

- name: Cleanup broadcom-wl
  ansible.builtin.file:
    path: ./broadcom-wl
    state: absent