---
- name: Add EPEL repository
  ansible.builtin.yum_repository:
    name: epel
    description: EPEL repo
    baseurl: https://download.fedoraproject.org/pub/epel/{{ansible_distribution_major_version}}/$basearch/
  become: true

- name: Add Microsoft repository (1/2)
  ansible.builtin.yum_repository:
    name: fedora
    enabled: true
    gpgcheck: true
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc
    description: Microsoft repos
    file: microsoft
    baseurl: https://packages.microsoft.com/fedora/{{ansible_distribution_major_version}}/prod
  become: true

- name: Add Microsoft repository (2/2)
  ansible.builtin.yum_repository:
    name: rhel
    enabled: true
    gpgcheck: true
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc
    description: Microsoft repos
    file: microsoft
    baseurl: https://packages.microsoft.com/rhel/8/prod
  become: true

- name: Add RPM Fusion repositories
  ansible.builtin.dnf:
    name: 
      - https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ansible_distribution_major_version}}.noarch.rpm
      - https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ansible_distribution_major_version}}.noarch.rpm
    state: present
    disable_gpg_check: true
  become: true

- name: Install packages
  ansible.builtin.dnf:
    name:
      - arduino
      - curl
      - firefox
      - git
      - gnupg
      - gzip
      - hashcat
      - htop
      - httping
      - iftop
      - llvm
      - netcat
      - nmap
      - openssl
      - p7zip
      - unzip
      - wget
      - whois
      - zmap
      - zsh
      - gtkhash
      - ffmpeg
      - ffmpeg-libs
      - fuse-exfat
      - exfat-utils
      - peek
      - powershell
      - hdparm
      - pv
    update_cache: true
    state: present
  become: true
