---
- name: Install i3
  dnf:
    name:
      - '@i3 desktop'
      - exfatprogs
      - htop
      - git
      - unzip
      - p7zip
      - zmap
      - nmap
      - netcat
      - gzip
      - curl
      - gnupg
      - whois
      - wget
      - openssl
      - fontawesome-fonts
      - nitrogen
      - alsa-utils
      - rxvt-unicode
    state: latest
  become: yes

- name: Touch .xinitrc
  file:
    path: /home/{{ ansible_user_id }}/.xinitrc
    state: touch
    owner: "{{ ansible_user_id }}"
    mode: '0744'

- name: Edit .xinitrc
  lineinfile:
    dest: /home/{{ ansible_user_id }}/.xinitrc
    line: 'exec i3'
    state: present
    
- name: Copy i3 config
  copy:
    src: i3config
    dest: ~/.config/i3/config
    owner: "{{ ansible_user_id }}"
    mode: '0744'

- name: Copy i3status config
  copy:
    src: i3statusconfig
    dest: ~/.config/i3status/config
    owner: "{{ ansible_user_id }}"
    mode: '0744'
