---
- name: Extend partition
  ansible.builtin.command:
    cmd: growpart /dev/mmcblk0 3
  ignore_errors: true
  become: true

- name: Extend volume
  ansible.builtin.command:
    cmd: resize2fs /dev/mmcblk0p3
  ignore_errors: true
  become: true
