---
- name: Add Ubuntu main/universe/restricted
  apt_repository:
    repo: deb http://archive.ubuntu.com/ubuntu {{ansible_distribution_release}} main universe restricted
    state: present
  become: yes
    
- name: Install Microsoft repo
  command: curl -sSL https://packages.microsoft.com/config/ubuntu/20.04/prod.list | sudo tee /etc/apt/sources.list.d/microsoft-prod.list
  become: yes

- name: Install software
  apt:
    name:
      - git
      - ansible
      - virt-manager
      - 
    state: latest
  become: yes
