---
- name: Add Ubuntu main/universe/restricted
  apt_repository:
    repo: deb http://archive.ubuntu.com/ubuntu {{ansible_distribution_release}} main universe restricted
    state: present
  become: yes

- name: Install software
  apt:
    name:
      - git
      - ansible
      - exfat-fuse
      - exfat-utils
      - gtkhash
      - virtualbox
      - gnome-tweak-tool
      - libglib2.0-dev
    state: latest
  become: yes
