---
- name: Add Ubuntu main/universe/restricted
  apt_repository:
    repo: deb http://archive.ubuntu.com/ubuntu {{ansible_distribution_release}} main universe restricted
    state: present
  become: yes

- name: Install software
  apt:
    name:
      - git
      - ansible
      - exfat-fuse
      - gtkhash
      - virtualbox
      - virtualbox-ext-pack
      - libglib2.0-dev
      - network-manager-openconnect-gnome
      - gnome-session
      - gnome-screenshot
    state: present
  become: yes
