---
- name: Add Ubuntu main/universe/restricted
  apt_repository:
    repo: deb http://archive.ubuntu.com/ubuntu {{ansible_distribution_release}} main universe restricted
    state: present
  become: true

- name: Install software
  apt:
    name:
      - docker
      - docker-compose
    state: latest
  become: true

- name: Add ubuntu to docker group
  ansible.builtin.user:
    name: ubuntu
    groups: docker
  append: true