---
- name: Install snaps (--classic)
  community.general.snap:
    name:
      - code
      - powershell
    classic: yes
  become: yes
    
- name: Install snaps
  community.general.snap:
    name:
      - teams
      - zoom-client
      - brave
  become: yes
