---
- name: Install software
  apt:
    name:
      - git
      - ansible
      - exfat-fuse
      - exfat-utils
      - gtkhash
      - virtualbox
      - build-essentials
      - dkms
      - linux-headers-generic
    state: latest
  become: yes
