---
- name: Install software
  ansible.builtin.apt:
    name:
      - git
      - ansible
      - exfat-fuse
      - gtkhash
      - virtualbox
      - virtualbox-ext-pack
      - virtualbox-dkms
      - dkms
      - linux-headers-generic
    state: present
  become: true
