---
- name: Add Microsoft repository
  ansible.builtin.yum_repository:
    name: rhel
    enabled: true
    gpgcheck: true
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc
    description: Microsoft repos
    file: microsoft
    baseurl: https://packages.microsoft.com/rhel/8/prod
  become: true

- name: Add Epel
  ansible.builtin.dnf:
    name:
      - http://download.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
    state: present
    disable_gpg_check: true
  become: true

- name: Add CentOS Plus
  ansible.builtin.yum_repository:
    name: centosplus
    enabled: true
    gpgcheck: true
    gpgkey: http://mirror.centos.org/centos/RPM-GPG-KEY-CentOS-8
    description: CentOS Plus repos
    file: centos-plus
    mirrorlist: http://mirrorlist.centos.org/?release=$releasever&arch=$basearch&repo=centosplus
  become: true

- name: Install packages
  ansible.builtin.dnf:
    name:
      - curl
      - git
      - gnupg
      - gzip
      - nmap
      - openssl
      - unzip
      - wget
      - whois
      - powershell
      - virt-manager
    update_cache: true
    state: present
  become: true
