---
- name: Add the flathub repository
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
  become: true

- name: Install flatpaks
  community.general.flatpak:
    name:
      - com.visualstudio.code
      - org.gnome.seahorse.Application
      - org.videolan.VLC
      - org.gtkhash.gtkhash
      - us.zoom.Zoom
      - com.microsoft.Teams
      - com.uploadedlobster.peek
      - com.brave.Browser
  become: true
