---
- name: Pi
  ansible.builtin.include_tasks: tasks/pi.yml
  when: ansible_facts['architecture'] == 'armv7l'
- name: Update
  ansible.builtin.include_tasks: tasks/update.yml
- name: DNF
  ansible.builtin.include_tasks: tasks/dnf.yml
  when: ansible_facts['memtotal_mb'] > 1000
- name: Flatpak
  ansible.builtin.include_tasks: tasks/flatpak.yml
  when: ansible_facts['memtotal_mb'] > 1000
- name: Broadcom Wireless
  ansible.builtin.include_tasks: tasks/broadcom-wl.yml
  when: ansible_facts['product_name'] == '334777U'
- name: PIA
  ansible.builtin.include_tasks: tasks/pia.yml
  when: ansible_facts['memtotal_mb'] > 1000
- name: Reboot
  ansible.builtin.include_tasks: tasks/reboot.yml