---
- name: Fedora playbook
  hosts: all

  vars_files:
    - default.config.yml

  tasks:
    - include_tasks: tasks/update.yml
    - include_tasks: tasks/dnf.yml
    - include_tasks: tasks/flatpak.yml
    - include_tasks: tasks/broadcom-wl.yml
      when: ansible_facts['product_name'] == ''
    - include_tasks: tasks/pia.yml
    - include_tasks: tasks/reboot.yml