name: Ansible Lint
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Ansible Lint
        uses: ansible-community/ansible-lint-action@v6.0.2
        with:
         args: "bootstrap.yml"
